details:
  namespace: student17-bookinfo-prd
  image: ghcr.io/62130500017/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-github
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.opsta.net
  path: "/student17/details(/|$)(.*)"
  serviceType: ClusterIP
